#!/usr/bin/php
<?php
// This deploy hook gets executed after dependencies are resolved and the
// build hook has been run but before the application has been started back
// up again.  This script gets executed directly, so it could be python, php,
// ruby, etc.
$repoDir = getenv('OPENSHIFT_REPO_DIR');
$cmd = "ln -s {$repoDir}web {$repoDir}php";
echo $cmd . "\n";
echo `$cmd`;

$dataDir = getenv('OPENSHIFT_DATA_DIR');
$vendorsDir = "{$dataDir}symfony2_vendor";
if (!is_dir($vendorsDir)) {
	mkdir($vendorsDir);
}
$cmd = "ln -s {$vendorsDir} {$repoDir}vendor";
echo $cmd . "\n";
echo `$cmd`;

chdir($repoDir);
echo `curl -sS https://getcomposer.org/installer | php`;

$cmd = "cp {$repoDir}.openshift/app_data/parameters.yml {$repoDir}app/config/";
echo $cmd . "\n";
echo `$cmd`;

echo `./composer.phar install`;