#!/usr/bin/php
<?php
// This deploy hook gets executed after dependencies are resolved and the
// build hook has been run but before the application has been started back
// up again.  This script gets executed directly, so it could be python, php,
// ruby, etc.
$repoDir = getenv('OPENSHIFT_REPO_DIR');
$cmd = "ln -s {$repoDir}web {$repoDir}php";
echo $cmd . "\n";
echo `$cmd`;

chdir($repoDir);
echo `curl -sS https://getcomposer.org/installer | php`;

echo `./composer.phar install`;