application_portfolio:
    resource: "@ApplicationPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    pattern:   /design/login
    defaults:  { _controller: ApplicationPortfolioBundle:Default:login }
login_check:
    pattern:   /design/login_check
    defaults:  { _controller: ApplicationPortfolioBundle:Default:login_check }